version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: sail
        uid: 1000
    container_name: website-desa-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
    networks:
      - website-desa-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: website-desa-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - website-desa-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: website-desa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-data/db:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - website-desa-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: website-desa-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - website-desa-network
    depends_on:
      - db

networks:
  website-desa-network:
    driver: bridge
